name: BetterPreview
version: '${version}'
description: "Chat preview without the privacy concerns"
main: com.tisawesomeness.betterpreview.spigot.BetterPreviewSpigot
api-version: 1.19
authors: [ Tis_awesomeness ]
softdepend: [ EssentialsChat ]
permissions:
  betterpreview.preview:
    description: "Allows the user to use BetterPreview previews"
    default: true
