name: BetterPreview
version: '${version}'
description: "Chat preview without the privacy concerns"
main: com.tisawesomeness.betterpreview.spigot.BetterPreviewSpigot
api-version: 1.19
authors: [ Tis_awesomeness ]
softdepend: [ EssentialsChat, LPC ]
commands:
  betterpreview:
    description: "BetterPreview command"
    aliases: [ bp, preview ]
    permission: betterpreview.info
    permission-message: "§cYou do not have permission to use this command."
permissions:
  betterpreview.*:
    default: op
    children:
      betterpreview.preview: true
      betterpreview.refresh.*: true
  betterpreview.preview:
    description: "Allows the user to use BetterPreview previews"
    default: true
  betterpreview.refresh.*:
    description: "Allows refreshing the user's preview"
    default: op
    children:
      betterpreview.refresh: true
      betterpreview.refresh.others: true
      betterpreview.refresh.all: true
  betterpreview.refresh:
    description: "Allows refreshing the user's preview"
    default: op
    children:
      betterpreview.info: true
  betterpreview.refresh.others:
    description: "Allows refreshing the other players' preview"
    default: op
  betterpreview.refresh.all:
    description: "Allows refreshing all players' previews"
    default: op
